genderwatch/urls.py
"""URLS"""
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from genderwatch import views

urlpatterns = [
    url(r'^$', views.AssemblyListView.as_view(), name="assembly-list"),
    url(r'^assembly/(?P<pk>[0-9]+)/$', views.AssemblyDetailView.as_view(), name="assembly-detail"),
    url(r'^assembly/(?P<pk>[0-9]+)/edit/$', views.AssemblyUpdateView.as_view(), name="assembly-update"),
    url(r'^assembly/(?P<pk>[0-9]+)/delete/$', views.AssemblyDeleteView.as_view(), name="assembly-delete"),
    url(r'^assembly/create/$', views.AssemblyCreateView.as_view(), name="assembly-create"),
    url(r'^assembly/(?P<pk>[0-9]+)/stat/$', views.AssemblyStatView.as_view(), name="assembly-stat"),
    url(r'^init-verdict/(?P<pk>[0-9]+)/$', views.init_verdict, name="init-verdict"),
    url(r'^verdict/(?P<pk>[0-9]+)/edit/$', views.VerdictUpdateView.as_view(), name="verdict-update"),
    url(r'^verdict/(?P<pk>[0-9]+)/delete/$', views.VerdictDeleteView.as_view(), name="verdict-delete"),
    url(r'^verdict/$', views.update_verdict, name="update-verdict"),
    url(r'^event-create/$', views.event_create, name="event-create"),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(
        template_name='genderwatch/registration/login.html'), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(
        template_name='genderwatch/registration/logged_out.html'), name='logout'),
    url(r'^accounts/password-change/$', auth_views.PasswordChangeView.as_view(
        template_name='genderwatch/registration/password_change_form.html'),
        name='password_change'),
    url(r'^accounts/password-change/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='genderwatch/registration/password_change_done.html'),
        name='password_change_done'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import genderwatch.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(genderwatch.urls))
]

genderwatch/models.py
import datetime
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User, Group

# Create your models here.
GENDERS = (
    ('m', 'Männer*'),
    ('f', 'Frauen*'),
    ('a', 'Andere'),
)

POSITIONS = (
    ('GL', "Geschäftsleitung"),
    ('PR', "Präsidium"),
    ('VS', "Vorstand"),
    ('BA', "Basis"),
    ('DG', "Delegierte"),
    ('GA', "Gäst*innen"),
    ('PO', "Podium"),
    ('NR', "Nationalrat"),
    ('BR', "Bundesrat"),
    ('SR', "Ständerat"),
    ('KR', "Kantonsrat"),
    ('GR', "Grossrat"),
    ('LR', "Landrat"),
    ('RR', "Regierungsrat"),
    ('STR', "Stadtrat"),
    ('GER', "Gemeinderat"),
    ('ER', "Einwohnerrat"),
    ('HA', "Hauptamtlich"),
    ('EA', "Ehrenamtlich"),
)

def get_position_display(short):
    for position in POSITIONS:
        if short == position[0]:
            return position[1]
    return '--'


class Assembly(models.Model):
    """
    Versammlungen, Workshops usw.
    """
    CATEGORIES = (
        ('SI', "Sitzung"),
        ('DV', 'Delegiertenversammlung'),
        ('SEKO', "Sektionskonferenz"),
        ('JV', "Jahresversammlung"),
        ('BV', "Bildungsveranstaltung"),
        ('VV', "Vollversammlung"),
        ('MV', "Mitgliederversammlung"),
        ('GRS', "Grossratssitzung"),
        ('KRS', "Kantonsratssitzung"),
        ('NRS', "Nationalratssitzung"),
        ('SRS', "Ständeratssitzung"),
        ('STRS', "Stadtratssitzung"),
        ('GERS', "Gemeinderatssitzung"),
        ('ERS', "Einwohnerratssitzung"),
    )

    category = models.CharField(max_length=10, choices=CATEGORIES, verbose_name="Kategorie")
    title = models.CharField(max_length=100, verbose_name="Titel")
    location = models.CharField(max_length=100, verbose_name="Ort")
    date = models.DateField()
    user = models.ManyToManyField(User, verbose_name="Prtokollierende")
    closed = models.BooleanField(default=False)
    positions = models.CharField(max_length=100, default='GL,DG', verbose_name="Positionen")
    topics = models.TextField(default="Begrüssung\nTraktandum 1", verbose_name="Themen")

    def get_topics(self):
        return [(slugify(t), t) for t in self.topics.strip().split('\n')]

    def get_absolute_url(self):
        """
        Return url to this object
        """
        from django.urls import reverse
        return reverse('assembly-detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

    def short_summary(self):
        for gender in GENDERS:
            durations = [verdict.duration() for verdict in self.verdict_set.filter(gender=gender[0])]
            duration = sum(durations, datetime.timedelta())
            hours = int(duration.total_seconds()/3600)
            minutes = int(duration.total_seconds() % 3600 / 60)
            seconds = int(duration.total_seconds() % 60)

            yield (gender, '{:0>2}:{:0>2}:{:0>2}'.format(hours, minutes, seconds), len(durations))

    def gender_count(self, gender):
        return self.verdict_set.filter(gender=gender).count()

    def gender_time(self, gender):
        durations = [verdict.duration() for verdict in self.verdict_set.filter(gender=gender)]
        duration = sum(durations, datetime.timedelta())
        return duration.total_seconds()/60

    def time_graph(self):
        import plotly.offline as py
        import plotly.graph_objs as go

        x = list(g[1] for g in GENDERS)
        data = []
        for position in set(self.verdict_set.values_list('position', flat=True)):
            y = list(sum((v.duration() for v in self.verdict_set.filter(gender=g[0], position=position)),\
                         datetime.timedelta()).total_seconds()/60 for g in GENDERS)

            data.append(go.Bar(
                x=x,
                y=y,
                name=get_position_display(position)
            ))

        layout = go.Layout(
            title=str(int(sum((v.duration() for v in self.verdict_set.all()), datetime.timedelta()).\
                    total_seconds()/60))+ " Min. Redezeit",
            barmode='stack',
            yaxis = dict(
                title="Minuten"
            ),
        )
        fig = go.Figure(data=data, layout=layout)
        print(data)
        return py.plot(fig, include_plotlyjs=False, output_type="div")

    def count_graph(self):
        import plotly.offline as py
        import plotly.graph_objs as go

        x = list(g[1] for g in GENDERS)
        data = []
        for position in set(self.verdict_set.values_list('position', flat=True)):
            y = list(self.verdict_set.filter(gender=g[0], position=position).count() for g in GENDERS)

            data.append(go.Bar(
                x=x,
                y=y,
                name=get_position_display(position)
            ))

        layout = go.Layout(
            barmode='stack',
            title=str(self.verdict_set.count()) + " Wortmeldungen",
        )
        fig = go.Figure(data=data, layout=layout)
        print(data)
        return py.plot(fig, include_plotlyjs=False, output_type="div")

    def count_category(self, gender, category):
        return self.verdict_set.filter(category=category, gender=gender).count()

    def category_count_chart(self):
        import plotly.offline as py
        import plotly.graph_objs as go
        data = []

        for gender in GENDERS:
            x = list((v[1] for v in self.get_topics()))
            y = list((self.count_category(gender[0], c[0]) for c in self.get_topics()))
            trace = go.Bar(
                x=x,
                y=y,
                name=gender[1],
            )
            data.append(trace)

        layout = go.Layout(
            title="Anzahl Wortmeldungen pro Kategorie",
            yaxis = dict(
                title="#"
            ),
            xaxis = dict(
                title="Kategorie"
            ),
            barmode="group"
        )
        fig = go.Figure(data=data, layout=layout)
        return py.plot(fig, include_plotlyjs=False, output_type="div")

    def time_category(self, gender, category):
        durations = (v.duration() for v in self.verdict_set.filter(category=category, gender=gender))
        duration = sum(durations, datetime.timedelta())
        return duration.total_seconds()/60


    def category_time_chart(self):
        import plotly.offline as py
        import plotly.graph_objs as go
        data = []

        for gender in GENDERS:
            x = list((v[1] for v in self.get_topics()))
            y = list((self.time_category(gender[0], c[0]) for c in self.get_topics()))
            trace = go.Bar(
                x=x,
                y=y,
                name=gender[1],
            )
            data.append(trace)

        layout = go.Layout(
            title="Redezeit pro Kategorie",
            yaxis = dict(
                title="Minuten"
            ),
            xaxis = dict(
                title="Kategorie"
            ),
            barmode="group"
        )
        fig = go.Figure(data=data, layout=layout)
        return py.plot(fig, include_plotlyjs=False, output_type="div")

    def position_count_chart(self):
        import plotly.offline as py
        import plotly.graph_objs as go
        data = []
        labels = []
        values = []
        for position in self.verdict_set.values_list('position', flat=True):
            for gender in GENDERS:
                value = self.verdict_set.filter(gender=gender[0], position=position).count()
                if value > 0:
                    values.append(value)
                    labels.append('{} {}'.format(position, gender[1]))

        trace = go.Pie(
            labels=labels,
            values=values,
        )
        data.append(trace)

        layout = go.Layout(
            title=str(self.verdict_set.count()) + " Wortmeldungen",
        )
        fig = go.Figure(data=data, layout=layout)
        return py.plot(fig, include_plotlyjs=False, output_type="div")

    def position_time_chart(self):
        import plotly.offline as py
        import plotly.graph_objs as go
        labels = []
        values = []
        for position in self.verdict_set.values_list('position', flat=True):
            for gender in GENDERS:
                value = sum((v.duration() for v in self.verdict_set.filter(gender=gender[0],
                                                                           position=position)), datetime.timedelta()).total_seconds()/60
                if value > 0:
                    values.append(value)
                    labels.append('{} {}'.format(position, gender[1]))

        trace = go.Pie(
            labels=labels,
            values=values,
        )
        layout = go.Layout(
            title=str(int(sum((v.duration() for v in self.verdict_set.all()), datetime.timedelta()).\
                    total_seconds()/60))+ " Min. Redezeit",
        )
        fig = go.Figure(data=[trace], layout=layout)
        return py.plot(fig, include_plotlyjs=False, output_type="div")

    def gender_graph(self):
        import plotly.offline as py
        import plotly.graph_objs as go
        from plotly import tools
        fig = {
            'data': [],
            'layout': {'title': 'Gendergerechte Sprache',
                       'showlegend': False,
                       "annotations": []
                      }
        }
        data = []
        domains = [
            {'x':[0,1/3.],'y':[0,1]}, 
            {'x':[1./3,2./3],'y':[0,1]}, 
            {'x':[2./3,1],'y':[0,1]}, 
        ]

        for i, gender in enumerate(Verdict.GENDERS):
            gp = Event.objects.filter(gender=gender[0],\
                                                 verdict__assembly=self, category='G+').count()
            gm =             Event.objects.filter(gender=gender[0],\
                                                 verdict__assembly=self, category='G-').count()

            fig['data'].append(
                go.Pie(

genderwatch/forms.py
"""
forms
"""
from django import forms
from django.forms import ModelForm
from genderwatch.models import Verdict, Event

class VerdictForm(ModelForm):
    """
    Form for providing infos about a verdict.
    """
    gender = forms.ChoiceField(choices=Verdict.GENDERS, widget=forms.RadioSelect)
    position = forms.ChoiceField(choices=Verdict.POSITIONS, widget=forms.RadioSelect)
    category = forms.ChoiceField(choices=Verdict.CATEGORIES)

    def __init__(self, *args, **kwargs):
        assembly = kwargs.get('assembly', None)
        del kwargs['assembly']
        super(VerdictForm, self).__init__(*args, **kwargs)
        positions = assembly.positions.replace(' ', '').split(',')
        categories = assembly.get_topics()
        choices = [(p[0], p[1]) for p in Verdict.POSITIONS if p[0] in positions]
        self.fields['position'].choices = choices
        self.fields['category'].choices = categories

    class Meta:
        model = Verdict
        fields = ['gender', 'position', 'category']

class EventForm(ModelForm):
    """
    Form for creating an event
    """
    def __init__(self, *args, **kwargs):
        button_text = kwargs.get('button_text', '')
        if button_text:
            del kwargs['button_text']
        super(EventForm, self).__init__(*args, **kwargs)
        self.button_text = button_text
        
    class Meta:
        model = Event
        fields = ['gender', 'position', 'category']
        widgets = {
            'gender': forms.HiddenInput(),
            'position': forms.HiddenInput(),
            'category': forms.HiddenInput(),
        }

genderwatch/templates/genderwatch/assembly_confirm_delete.html
{% extends 'genderwatch/base.html' %}
{% block title %}
Genderwatch
{% endblock title %}
{% block header %}
<h1>{{object.title}} löschen</h1>
{% endblock header %}

{% block content %}
<form action="" method="post">{% csrf_token %}
	<p>Bist du sicher, dass du diese Versammlung löschen willst?</p>
	<ul>
		<li>{{object.title}}</li>
	</ul>
    <input type="submit" value="Bestätigen" class="btn btn-c smooth" />
</form>

{% endblock %}

genderwatch/templates/genderwatch/assembly_detail.html
{% extends 'genderwatch/base.html' %}

{%block title %}{{assembly.title}}
{% endblock title %}

{% block header %}
<h1>{{assembly.title}} <small>({{assembly.date|date:"d.M. Y"}})</small></h1>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col c12">
    {% if not object.closed %}
		<button onclick="window.location.href='{% url 'init-verdict' pk=object.pk %}'" class="btn btn-b smooth">Neue Wortmeldung</button>
    {% endif %}
		<button onclick="window.location.href='{% url 'assembly-stat' pk=object.pk %}'" class="btn btn-b smooth">Statistik</button>
	{% if perms.genderwatch.change_assembly %}
		<button onclick="window.location.href='{% url 'assembly-update' pk=object.pk %}'" class="btn btn-b smooth">Bearbeiten</button>

	{% endif %}

	</div>
	<div class="col c12">
		<h2>Bisherige Wortmeldungen</h2> 
		<table class="table">
			<thead>
				<th>#</th>
				<th>Gender</th>
				<th>Position</th>
				<th>Kategorie</th>
				<th>Start</th>
				<th>Ende</th>
				<th>Protkolliert von</th>
			</thead>
			<tbody>
				{% for verdict in assembly.verdict_set.all %}
				<tr>
					<td>{% if perms.genderwatch.change_verdict %}
						<a href="{% url 'verdict-update' verdict.pk %}">
							{{forloop.counter}}</a>
						{% else %}
						{{forloop.counter}}
						{% endif %}
					</td>
					<td>{{verdict.get_gender_display}}</td>
					<td>{{verdict.get_position_display}}</td>
					<td>{{verdict.get_category_name}}</td>
					<td>{{verdict.start|date:"H:i"}}</td>
					<td>{{verdict.end|date:"H:i"}}</td>
					<td>{{verdict.user}}</td>
				</tr>

				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col c12">
		<h2>Kurze Zusammenfassung</h2>
		<table class="table">
			<thead>
				<tr>
					<th>Gender</th>
					<th>Redezeit</th>
					<th>Anzahl Wortmeldungen</th>
				</tr>
			</thead>
			<tbody>
				{% for gender in assembly.short_summary %}
				<tr>
					<td>{{gender.0.1}}</td>
					<td class="right">{{gender.1}}</td>
					<td class="right">{{gender.2}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>

		<br>
	</div>
	<div class="col c12">
		<button onclick="window.location.href='{% url 'assembly-list' %}'" class="btn btn-a smooth">Zurück zur Übersicht</button>
	</div>
</div>
{% endblock %}

genderwatch/templates/genderwatch/assembly_form.html
{% extends 'genderwatch/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{% if object %}
"{{object.title}}" bearbeiten
{% else %}
Neue Versammlung
{% endif %}
{% endblock title %}

{% block header %}
{% if object %}
<h2>"{{object.title}}" bearbeiten</h2>
{% else %}
<h2>Neue Versammlung</h2>
{% endif %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col c6">
		<form action="" method="POST" class="uni-form">
			{% csrf_token %}
			{{form}}

			<div class="button-holder">
				<button type="submit" class="btn btn-b smooth">Absenden</button>
			</div>

		</form>
	</div>
	<div class="col c6">
		<h2>Hilfe</h2>
		<p>
		Hier kannst du eine neue Versammlung erstellen oder eine bestehende bearbeiten.
		Dazu musst du den Namen, den Ort und das Datum der Versammlung eintragen.
		</p>
		<p>
		Unter Protokollierende kannst du die Accounts auswählen, die die Veranstaltung protokollieren sollen. Vergiss nicht, dich selber auch auszuwählen, ansonsten hast du keinen Zugriff mehr auf die Versammlung! Unter Positionen kannst du auswählen, wer alles an der Veranstaltung sprechen wird. Zur Verfügung stehen:
		<ul>
			<li>GL, Geschäftsleitung</li>
			<li>VS, Vorstand</li>
			<li>BA, Basis</li>
			<li>DG, Delegierte</li>
			<li>GA, Gäst*innen</li>
			<li>PO, Podium</li>
			<li>WS, Workshopleitung</li>
            <li>NR, Nationalrat</li>
            <li>BR, Bundesrat</li>
            <li>SR, Ständerat</li>
            <li>KR, Kantonsrat</li>
            <li>GR, Grossrat</li>
            <li>LR, Landrat</li>
            <li>RR, Regierungsrat</li>
            <li>STR, Stadtrat</li>
            <li>GER, Gemeinderat</li>
            <li>ER, Einwohnerrat</li>
        </ul>
        <p>
        Unter Themen kannst du die Themen eintragen, die an der Versammlung behandelt werden.
        Trage dabei jedes Thema in eine neue Zeile ein.
        </p>
    </div>
</div>
{% endblock %}

genderwatch/templates/genderwatch/assembly_list.html
{% extends 'genderwatch/base.html' %}
{% block title %}
Genderwatch
{% endblock title %}
{% block header %}
<h1>Genderwatch</h1>
{% if perms.genderwatch.add_assembly %}
<h2>
<a href="{% url 'assembly-create' %}">Veranstaltung erstellen</a>
</h2>
{% endif %}
{% endblock header %}

{% block content %}
<div class="row">
	<div class="col c12">
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Ort</th>
					<th>Datum</th>
					<th>Kategorie</th>
					<th>Aktion</th>

				</tr>
			</thead>
			<tbody>
				{% for assembly in object_list %}
				<tr>
					<td>{{assembly.title}}</td>

					<td>{{assembly.location}}</td>
					<td>{{assembly.date|date:"j.b. Y"}}
					<td>{{assembly.get_category_display}}</td>
					<td><a href="{{assembly.get_absolute_url}}">Überblick</a>{% if perms.genderwatch.change_assembly %} | <a href="{% url 'assembly-update' assembly.pk %}">Bearbeiten</a>{% endif%}
{% if perms.genderwatch.delete_assembly %} | <a href="{% url 'assembly-delete' assembly.pk %}">Löschen</a>{% endif%}
					</td>
					{% endfor %}
				</tr>
			</tbody>

		</table>
	</div>
</div>
{% endblock %}

genderwatch/templates/genderwatch/assembly_stat.html
{% extends 'genderwatch/base.html' %}
{% block title %}
{{assembly.title}}
{% endblock title %}

{% block header %}
<h1>{{assembly.title}}</h1>
{% endblock %}

{% block content %}

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>


<div class="row">
<div class="col c6">
{{assembly.count_graph|safe}}
</div>
<div class="col c6">
{{assembly.time_graph|safe}}
</div>
<div class="col c12">
{{assembly.category_count_chart|safe}}
</div>
<div class="col c12">
{{assembly.category_time_chart|safe}}
</div>
<div class="col c6">
{{assembly.position_count_chart|safe}}
</div>
<div class="col c6">
{{assembly.position_time_chart|safe}}
</div>
<div class="col c12">
{{assembly.gender_graph|safe}}
</div>
<div class="col c12">
{{assembly.interruptions_graph|safe}}
</div>
<div class="col c12">
{{assembly.sexism_graph|safe}}
</div>

	<div class="col c12">
		<button onclick="window.location.href='{% url 'assembly-list' %}'" class="btn btn-a smooth">Zurück zur Übersicht</button>
	</div>
</div>

{% endblock %}

genderwatch/templates/genderwatch/event_create.html
{% extends 'genderwatch/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Event erfassen
{% endblock title %}
{% block header %}
<h1>{{assembly.title}} <small>({{assembly.date|date:"d.M. Y"}})</small></h1>
<h2>Event erfassen</h2>
{% endblock %}
{% block extra_css %}
.button-holder {
	padding: 1em;
}
.btn {
	width: 100%;
}
{% endblock %}
{% block content %}
<div class="row">
		{% for form in forms.glang %}
	<div class="col c3">
		<form action="" method="POST" class="">
			{% csrf_token %}
			{{form}}

			<div class="button-holder">
				<button type="submit" class="btn btn-b smooth">
					{{form.button_text}}
				</button>
			</div>

		</form>
	</div>
		{% endfor %}
	<div class="col c3">
		<form action="" method="POST" class="">
			{% csrf_token %}
			{{forms.sexism}}

			<div class="button-holder">
				<button type="submit" class="btn btn-b smooth">
					{{forms.sexism.button_text}}
				</button>
			</div>

		</form>
	</div>
	<div class="col c3">
		<form action="" method="POST" class="">
			{% csrf_token %}
			{{forms.end}}

			<div class="button-holder">
				<button type="submit" class="btn btn-c smooth">
					{{forms.end.button_text}}
				</button>
			</div>

		</form>
	</div>
</div>
<div class="row">
		<h2>Unterbrechungen (durch)</h2>
		{% for position in forms.interrupt %}
		{% for form in position %}
	<div class="col c4">
		<form action="" method="POST" class="">
			{% csrf_token %}
			{{form}}

			<div class="button-holder">
				<button type="submit" class="btn btn-b smooth">
					{{form.button_text}}
				</button>
			</div>

		</form>
	</div>
		{% endfor %}
		{% endfor %}
</div>
{% endblock %}

genderwatch/templates/genderwatch/index.html
{% extends 'genderwatch/base.html' %}

{% block header %}
<h1>Genderwatch Protokoll</h1>
{% endblock %}

{% block content %}
<a href="{% url 'assembly-list' %}">Zur Übersicht</a>
{% endblock %}

genderwatch/templates/genderwatch/verdict_confirm_delete.html
{% extends 'genderwatch/base.html' %}
{% block title %}
Genderwatch
{% endblock title %}
{% block header %}
<h1>Wortmeldung löschen</h1>
{% endblock header %}

{% block content %}
<form action="" method="post">{% csrf_token %}
	<p>Bist du sicher, dass du diese Wortmeldung löschen willst?</p>
	<ul>
		<li>{{object.get_gender_display}}</li>
		<li>{{object.get_position_display}}</li>
		<li>{{object.get_category_name}}</li>
		<li>{{object.start}} - {{object.end}}</li>
	</ul>

    <input type="submit" value="Bestätigen" class="btn btn-c smooth" />
    <a href="{{ view.get_success_url }}" class="btn btn-a smooth">Abbrechen</a>

</form>

{% endblock %}

genderwatch/templates/genderwatch/verdict_form.html
{% extends 'genderwatch/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Wortmeldung bearbeiten
{% endblock title %}

{% block header %}
<h2>Wortmeldung bearbeiten</h2>
<a href="{% url 'verdict-delete' object.pk %}" class="btn btn-c smooth btn-sm">Wortmeldung löschen</a>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col c6">
		<form action="" method="POST" class="uni-form">
			{% csrf_token %}
			{{form}}

			<div class="button-holder">
				<button type="submit" class="btn btn-b smooth">Absenden</button>
			</div>

		</form>
	</div>
	<div class="col c6">
		<h2>Hilfe</h2>
		<p>{{object.category}}
		</p>
	</div>
</div>
{% endblock %}

genderwatch/templates/genderwatch/verdict_update.html
{% extends 'genderwatch/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Neue Wortmeldung
{% endblock title %}

{% block extra_css %}

input[type=radio] {
-webkit-appearance: none;
-moz-appearance: none;
-ms-appearance: none;
-o-appearance: none;
appearance: none;
position: relative;
padding:0px;
top: 13.33333px;
right: 0;
bottom: 0;
left: 0;
height: 40px;
width: 40px;
transition: all 0.15s ease-out 0s;
background: #cbd1d8;
border: none;
color: #fff;
cursor: pointer;
display: inline-block;
margin-right: 0.5rem;
outline: none;
position: relative;
z-index: 1000;
}
input[type=radio]:hover {
background: #9faab7;
}
input[type=radio]:checked {
background: #40e0d0;
}
input[type=radio]:checked::before {
height: 40px;
width: 40px;
position: absolute;
content: '✓';
display: inline-block;
font-size: 26.66667px;
text-align: center;
line-height: 40px;
}
input[type=radio]:checked::after {
background: #40e0d0;
content: '';
display: block;
position: relative;
z-index: 100;
}
input[type=radio] {
border-radius: 50%;
}
input[type=radio]{
border-radius: 50%;
}

ul {
list-style: none;
padding-left: 10px;
margin-top: 0px;
padding-bottom: 17px;
}

{% endblock extra_css %}

{% block header %}
<h3 style="margin-bottom:0px">Neue Wortmeldung</h3>
{% endblock %}
{% block content %}
<div class="row" style="margin-top:0px">
  <div class="col c12" style="margin-top:0px">
    <form action="" method="POST" class="uni-form" style="margin-top:0px">
      {% csrf_token %}
      {{form}}

      <div class="button-holder">
        <button type="submit" class="btn btn-b smooth">Absenden</button>
      </div>

    </form>
  </div>
</div>
{% endblock %}